# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
   disable_csrf_role: none
   param_fetcher_listener:  true
   allowed_methods_listener:  true
   view:
       view_response_listener:  true
   exception:
       enabled: true  
#        codes:
#            App\Controller\Exception: 403
#        messages:
#            App\Controller\Exception: Forbidden area.
   format_listener:
       rules:
           - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
           - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
